import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "designing-transparent-payment-quotes",
  title: "Designing a payment quote users can trust",
  metaTitle: "Designing a Payment Quote Users Can Trust",
  description:
    "How to present rates, fees, expiry and the landed amount in a crypto-to-local-currency transfer, so the number the recipient receives is never a surprise.",
  category: "Crypto-to-fiat",
  published: "2026-09-21",
  readingMinutes: 7,
  keywords: [
    "payment quote design",
    "transparent transfer fees",
    "FX rate disclosure",
    "quote expiry",
    "landed amount",
  ],
  summary:
    "Users judge a transfer on one number: how much arrives. A trustworthy quote states that number first, itemises every cost that produced it, names the rate used, and says how long it is valid.",
  body: [
    { type: "p", text: "Quote design is where a cross-border payment product earns or loses trust, and it happens before any money moves. The failure is rarely that fees are high. It is that the landed amount does not match what the user expected, and nothing in the original quote explains why. Fixing that is a presentation problem with a small number of concrete rules." },
    { type: "h2", text: "Rule 1: lead with the landed amount" },
    { type: "p", text: "The recipient's amount, in the recipient's currency, is the headline. Not the send amount, not the fee, not the rate. Everything else is supporting detail that explains how that figure was produced. When a product leads with \"low fees\" instead, users correctly infer that the landed amount is the less flattering number." },
    { type: "h2", text: "Rule 2: itemise every cost" },
    { type: "p", text: "A crypto-to-local-currency transfer has at least four costs, and a single \"total fee\" line hides which one is large. Show them separately:" },
    { type: "ul", items: [
      "Network fee — what the blockchain charges to include the deposit.",
      "Conversion cost — the spread between the mid-market rate and the executed rate on the crypto leg, including slippage.",
      "Platform fee — your own charge, as a percentage and as an amount.",
      "Payout fee and FX margin — the institution's charge for delivering local currency, and any margin applied to the fiat rate.",
    ]},
    { type: "p", text: "Itemising invites comparison, which is the point. A user who can see each component and still proceeds has genuinely accepted the price." },
    { type: "h2", text: "Rule 3: name the rate and its source" },
    { type: "p", text: "\"Rate: 1 USDC = X\" is incomplete. State whether it is indicative or executable, when it was retrieved, and how it relates to the mid-market rate. If the rate is indicative — which it is in any demo or pre-partner state — say so in the same visual element as the number, not in a footnote." },
    { type: "callout", title: "Indicative means indicative", text: "If a rate cannot currently be executed, label it at the point of display. Burying that in terms and conditions while showing a precise figure reads as a real quote, and users will hold you to it." },
    { type: "h2", text: "Rule 4: make expiry visible and honest" },
    { type: "p", text: "Crypto legs are priced against moving markets. A quote must therefore have a lifetime, and the interface must show it — a countdown, a refresh action, and a clear statement of what happens when it lapses. Two anti-patterns to avoid: a quote that silently updates while the user reads it, and one that never expires and is then not honoured. Both teach the user that the number is decorative." },
    { type: "h2", text: "Rule 5: separate what is charged from what is estimated" },
    { type: "p", text: "Some components are known exactly at quote time; others are not. Network fees and platform fees are typically knowable. Final slippage and the payout partner's FX rate at execution may not be. Group them visually — \"fixed\" versus \"estimated, final amount confirmed at execution\" — and state the worst-case landed amount under your slippage tolerance. A guaranteed floor is far more reassuring than a precise-looking estimate." },
    { type: "h2", text: "Rule 6: show timing per leg, not one number" },
    { type: "p", text: "\"Arrives in minutes\" is usually wrong, because the on-chain leg takes seconds while the fiat payout leg follows banking hours and clearing cycles. Give a per-leg expectation: conversion in seconds, settlement to the payout institution the same day, local payout within the destination rail's window. Users tolerate a slower honest estimate; they do not tolerate an optimistic one that slips." },
    { type: "h2", text: "Rule 7: the receipt must match the quote, field for field" },
    { type: "p", text: "The receipt is where trust is settled. It should carry the same line items as the quote, with actuals beside estimates, plus the transaction signature so the on-chain leg is independently verifiable. Any difference between quoted and actual should be visible and explained, not quietly absorbed into a new total." },
    { type: "h2", text: "A checklist for the quote screen" },
    { type: "ol", items: [
      "Landed amount in the recipient's currency, largest element on screen.",
      "Send amount and asset, clearly the input.",
      "Rate used, with source and indicative-or-executable status.",
      "Four itemised cost lines, each with an amount.",
      "Fixed versus estimated grouping, with a worst-case floor.",
      "Expiry countdown and a refresh action.",
      "Per-leg timing expectations.",
      "Capability labels wherever a step is simulated, disabled or planned.",
      "One-line statement of who holds the funds at each stage.",
    ]},
    { type: "p", text: "LamportPay's transfer demo follows this structure. Rates shown are indicative and labelled, fees are itemised, and each step carries its capability status — the SOL-to-USDC conversion runs live against Solana under strict limits with output returning to the user's own wallet, while identity checks, fiat conversion and local payout are simulated pending a regulated payout infrastructure partner." },
  ],
  productLinks: [
    { to: "/send", label: "Transfer demo", note: "See the itemised quote, indicative rate labels and receipt structure." },
    { to: "/how-it-works", label: "How it works", note: "The route behind each quote line, step by step." },
    { to: "/compliance", label: "Compliance position", note: "Who holds funds at each stage, stated plainly." },
  ],
  relatedSlugs: ["crypto-to-fiat-payments-explained", "compliance-roles-in-crypto-payouts"],
};
