import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "web3-payment-rails-architecture",
  title: "Web3 payment rails: the reference architecture",
  metaTitle: "Web3 Payment Rails: Reference Architecture",
  description:
    "A component-by-component architecture for a Web3 payment rail — wallet layer, routing, verification, state machine, payout integration, and the observability that holds it together.",
  category: "Web3 payment rails",
  published: "2026-09-21",
  readingMinutes: 10,
  keywords: [
    "web3 payment rails",
    "payment orchestration architecture",
    "crypto payment infrastructure",
    "payment state machine",
    "webhook reconciliation",
  ],
  summary:
    "A Web3 payment rail is an orchestration layer over two very different systems. The architecture that works separates verifiable on-chain components from partner-dependent ones, and keeps a single authoritative state machine over both.",
  body: [
    { type: "p", text: "\"Payment rail\" is borrowed language, and it flatters most crypto payment products. A rail implies a network with rules, membership and dispute handling. What Web3 payment companies actually build is an orchestration layer: software that connects a public blockchain on one side to regulated financial institutions on the other, and keeps a coherent record across both. That is a narrower claim and a much more useful design brief." },
    { type: "h2", text: "The components" },
    { type: "h3", text: "1. Wallet layer" },
    { type: "p", text: "The user's key stays with the user. This layer connects to wallets, requests signatures for transactions the backend has built, and surfaces the connected address for verification. It should never handle key material, and it should refuse to display or accept a seed phrase in any context. Practically: adapters for the wallets your users actually have, a clear connected state, and an explicit indication of which address will receive any output." },
    { type: "h3", text: "2. Quoting and routing" },
    { type: "p", text: "Given an input asset and amount, this layer determines the route to the settlement asset and the expected output. On Solana, routing across liquidity venues is handled by aggregation infrastructure such as Jupiter; the orchestrator's job is to request a quote, apply its own limits and slippage policy, attach its fee transparently, and set an expiry. A quote without an expiry is a liability." },
    { type: "h3", text: "3. Transaction construction and submission" },
    { type: "p", text: "Build unsigned transactions server-side, where validation rules live and cannot be bypassed. Send them to the client for signature, accept the signed payload back, and submit it. This split keeps guards enforceable: allowed mints, amount ceilings and floors, and a destination restricted to the connected wallet. Any request carrying an unexpected destination field should be rejected outright rather than sanitised." },
    { type: "h3", text: "4. On-chain verification" },
    { type: "p", text: "A separate component that answers one question authoritatively: did this payment arrive, in the expected asset, in the expected amount, at the expected address, finally? It talks to RPC infrastructure, is cluster-aware, and is the only component permitted to move a payment into a state that triggers downstream money movement." },
    { type: "h3", text: "5. The state machine" },
    { type: "p", text: "This is the heart of the system, and the component most often deferred. Every payment is a row with an explicit status, a monotonic event log, and defined legal transitions. Everything else — user-facing status, receipts, admin tooling, reconciliation, analytics, support — reads from it." },
    { type: "ul", items: [
      "One authoritative status field, with transitions enforced in code rather than by convention.",
      "An append-only event table: what happened, when, triggered by what, with the external identifier involved.",
      "Idempotency keys on every mutating operation, so retries and duplicate webhooks collapse into one effect.",
      "A recorded reason on every terminal state, in language a support agent can read to a customer.",
    ]},
    { type: "h3", text: "6. Payout partner integration" },
    { type: "p", text: "The boundary to the regulated world. This layer creates customer records, submits payout instructions, and receives asynchronous status updates. Three rules keep it manageable: treat the partner's identifiers as foreign keys rather than your primary state, verify every inbound webhook signature before acting on it, and never let partner downtime corrupt your own state — queue and retry instead." },
    { type: "h3", text: "7. Operations and observability" },
    { type: "p", text: "A rail you cannot observe is a rail you cannot operate. The minimum is structured logs keyed by payment identifier across every leg, an admin view that shows a payment's full event history, alerting on stuck states rather than only on errors, and a daily reconciliation between on-chain facts, partner-reported payouts and your own ledger." },
    { type: "h2", text: "The seam that defines the design" },
    { type: "p", text: "Two of these components are verifiable by anyone — construction and on-chain verification. Two are entirely dependent on a counterparty — payout integration and the identity checks around it. The architecture's main job is to keep that seam visible instead of blurring it." },
    { type: "callout", title: "Design consequence", text: "Model partner-dependent legs as asynchronous by default, with their own statuses and their own timelines. A system that assumes the payout leg behaves like the on-chain leg will report false certainty, and false certainty is the most expensive bug in payments." },
    { type: "h2", text: "Ledger discipline" },
    { type: "p", text: "Once value crosses a boundary, a status field is not enough. Double-entry ledger entries — every movement recorded twice, against named accounts — are what make it possible to answer \"where is the money\" and \"do our books balance\" without reading application code. The accounts worth modelling early are the user's deposit, the platform's settlement balance, fee income, partner-held balance, and payout in flight. Retrofitting this after launch is significantly more painful than adding it before." },
    { type: "h2", text: "Security posture" },
    { type: "p", text: "The attack surface of a Web3 payment rail is unusual: one side is a public network where mistakes are irreversible, the other holds identity data. A short list that catches most of it:" },
    { type: "ul", items: [
      "All third-party credentials server-side, never in a client bundle, never in a public environment variable.",
      "Input validation on every endpoint with a schema, rejecting unknown fields rather than ignoring them.",
      "Row-level access control on every table holding customer or transaction data.",
      "Authorisation on operator endpoints, separate from end-user authentication, with an audit log for privileged actions.",
      "Webhook signature verification before any state change.",
      "Rate limiting on quoting and creation endpoints, which are the cheapest to abuse.",
    ]},
    { type: "h2", text: "A realistic build order" },
    { type: "ol", items: [
      "Wallet connection and on-chain verification — the components you can prove without any partner.",
      "Quoting and conversion into the settlement asset, with strict limits while it is young.",
      "State machine, event log and idempotency.",
      "Ledger entries and reconciliation.",
      "Admin tooling and structured logging.",
      "Deposit monitoring and automated status progression.",
      "Identity verification provider.",
      "Regulated payout partner and live fiat legs.",
      "Limit increases behind risk controls, then broader corridor coverage.",
    ]},
    { type: "p", text: "The ordering is deliberate: everything above step seven can be built, tested and demonstrated without a regulatory dependency, and each step makes the next one safer. LamportPay follows this sequence — the wallet, conversion and verification components run live under tight limits, the state and admin layers exist for the demonstrated flow, and the identity and fiat payout legs are labelled simulations pending a regulated payout infrastructure partner." },
  ],
  productLinks: [
    { to: "/docs", label: "Developer docs", note: "Stack, endpoints and architecture behind the demo." },
    { to: "/workflow", label: "Workflow overview", note: "Component-level integration status across the whole route." },
    { to: "/whitepaper", label: "White paper", note: "Longer-form architecture and roadmap." },
  ],
  relatedSlugs: ["crypto-to-fiat-payments-explained", "solana-payments-for-developers"],
};
