import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "why-stablecoins-settle-cross-border-payments",
  title: "Why stablecoins are the settlement asset for cross-border payments",
  metaTitle: "Why Stablecoins Settle Cross-Border Payments",
  description:
    "Stablecoins solve a specific problem in cross-border payments: pre-funding. Here is what they replace, what they do not replace, and the risks that remain.",
  category: "Stablecoins",
  published: "2026-09-21",
  readingMinutes: 8,
  keywords: [
    "stablecoin settlement",
    "USDC cross-border payments",
    "pre-funding nostro accounts",
    "stablecoin risk",
    "payment settlement layer",
  ],
  summary:
    "Stablecoins do not make payouts instant. They remove the need to pre-fund accounts in every destination country, which is the actual reason traditional cross-border transfers are slow and expensive.",
  body: [
    { type: "p", text: "The usual pitch for stablecoins in payments — \"money that moves in seconds for cents\" — is true about the token and misleading about the payment. The token moves in seconds. The payment still has to enter and leave the banking system at both ends, and those ends set the real timeline. So what do stablecoins genuinely fix?" },
    { type: "h2", text: "The problem they actually solve: pre-funding" },
    { type: "p", text: "To pay someone in another country quickly, a provider historically needs money already sitting in that country. That is pre-funding: capital parked in local accounts, per currency, per market, before a single customer transaction occurs. It is expensive in three separate ways." },
    { type: "ul", items: [
      "Capital cost — money sitting idle in twenty countries is money not doing anything else, and it has to be sized for peak volume, not average volume.",
      "FX exposure — balances held in local currency move against the provider's reporting currency every day.",
      "Operational cost — each account means a banking relationship, a reconciliation process, local reporting and a counterparty that can close the account.",
    ]},
    { type: "p", text: "Correspondent banking is the shared version of this arrangement: a chain of banks, each holding balances with the next, passing instructions along. That chain is why a transfer touches several intermediaries, why fees are hard to predict in advance, and why \"where is my money\" is frequently unanswerable mid-flight." },
    { type: "p", text: "A dollar-denominated stablecoin lets value move to the destination market at the moment it is needed, rather than being parked there in advance. The local institution receives a settlement asset it can convert and pay out, and the provider does not have to hold standing balances in every currency it serves. That is the structural change, and it is a large one." },
    { type: "h2", text: "What stablecoins do not solve" },
    { type: "p", text: "Being precise here matters, because overclaiming is what makes payment teams distrust the category." },
    { type: "ul", items: [
      "They do not remove identity checks. Paying a person in fiat requires KYC, sanctions screening and monitoring regardless of how the value arrived.",
      "They do not remove banking hours. The final leg lands on a domestic rail with its own cut-off times and clearing cycles.",
      "They do not remove FX. Converting a dollar stablecoin into local currency is still an FX trade with a spread, however it is dressed up.",
      "They do not remove the need for a licensed institution at the payout end.",
      "They do not eliminate float; they relocate it, from local currency accounts to the stablecoin itself.",
    ]},
    { type: "callout", title: "The honest summary", text: "Stablecoins compress the middle of a cross-border payment — the part between the sender's country and the recipient's country. The two ends still operate at the speed of banking and compliance." },
    { type: "h2", text: "Why the settlement asset is almost always a dollar stablecoin" },
    { type: "p", text: "Four properties make an asset usable as a settlement leg, and dollar stablecoins currently score highest on all four together." },
    { type: "ol", items: [
      "Price stability against the unit of account most quotes are expressed in, so the asset can be held between legs without introducing market risk.",
      "Liquidity depth on the chains and venues where conversion happens, so the conversion leg does not move the price.",
      "Institutional acceptance — payout institutions will actually receive it and credit an account against it.",
      "Programmability — balances and transfers are verifiable on-chain, which is what makes automated reconciliation possible.",
    ]},
    { type: "p", text: "USDC is the common choice for products that prioritise institutional acceptance and transparent reserve reporting. That choice is a trade-off like any other: it accepts issuer and jurisdictional concentration in return for the widest set of regulated counterparties willing to receive it." },
    { type: "h2", text: "The risks a payment team must actually price" },
    { type: "p", text: "Treating a stablecoin as \"a dollar\" in your risk model is a mistake. It is a claim on an issuer, transferred over a network, redeemable through specific channels. Each of those introduces a distinct risk." },
    { type: "h3", text: "Issuer and reserve risk" },
    { type: "p", text: "The token's value depends on the issuer holding and honouring redeemable reserves. Reserve composition, attestation frequency, and the operational route to redemption all matter. Concentration risk is real: a single issuer failing is not a market event you can hedge with a wider slippage tolerance." },
    { type: "h3", text: "De-peg and secondary market risk" },
    { type: "p", text: "Even a fully backed stablecoin can trade below par on secondary markets under stress, exactly when you most need to convert. If your conversion leg executes on a public venue, your effective rate is the secondary market rate, not the redemption rate." },
    { type: "h3", text: "Network risk" },
    { type: "p", text: "The chain carrying the settlement asset can degrade, congest or halt. Any product depending on one chain inherits its availability profile, which is an argument for chain-aware monitoring and, eventually, more than one settlement path." },
    { type: "h3", text: "Regulatory risk" },
    { type: "p", text: "Stablecoin rules are being written market by market, covering issuance, reserve requirements, and who may hold or distribute them. A settlement asset that is straightforward in one jurisdiction may require specific permissions in another. This is a live variable, not a settled question." },
    { type: "h2", text: "How this shapes a sensible architecture" },
    { type: "p", text: "If stablecoins are the settlement asset rather than the whole payment, the design follows naturally. Keep the settlement asset single and well-understood. Make the conversion leg into that asset a first-class, measurable component with its own quoting, limits and verification. Treat the fiat payout leg as an integration with a licensed institution, with its own status model and its own timeline expectations. And keep the two sides reconciled against on-chain facts, because that is the one place where you have an independent record." },
    { type: "p", text: "In LamportPay's architecture, USDC is the settlement asset and the conversion into it is the leg that runs live today: a strictly limited SOL-to-USDC swap routed through Jupiter on Solana, signed in the user's own wallet, with output returning to that same wallet. The fiat payout leg is presented as a labelled simulation pending a regulated payout infrastructure partner. That separation is the point — the settlement asset is chosen and proven before the regulated leg is switched on." },
  ],
  productLinks: [
    { to: "/whitepaper", label: "White paper", note: "Architecture and roadmap, including the role of USDC as settlement asset." },
    { to: "/swap", label: "SOL to USDC swap demo", note: "The live conversion leg, with strict amount limits and wallet-only output." },
    { to: "/workflow", label: "Workflow overview", note: "See which parts of the route are live, simulated or planned." },
  ],
  relatedSlugs: ["crypto-to-fiat-payments-explained", "solana-payments-for-developers"],
};
